### ISSUE TITLE
【依頼】最終課題挙動確認

### ISSUE THREAD

**Issue by usuke-inudog** [8hachi8/fleamarket_sample_78h#73]
■ URL
IPアドレス：http://18.181.128.231/
Github（最終課題のリポジトリ）：https://github.com/8hachi8/fleamarket_sample_78h

■ Basic認証
ID：team78h
Pass：shibuya

■ テスト用アカウント
◯ 購入者用
メールアドレス：sample1@sample.com
パスワード：0000000

◯ 購入用カード情報
番号：4242424242424242
期限：30/12
セキュリティコード：765

◯ 出品者用
メールアドレス：sample2@sample.com
パスワード：0000000

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①購入時、配送先の住所情報も都度入力できるようにしましょう
②購入時、クレジットカードの情報を都度入力できるようにしましょう
　（現在は一度登録すると変更ができない仕様になっています）
③購入時こちらのissueに記載されているカード情報を入力しても登録が完了しないので、登録できるようにしましょう**

また、上記により、下記の項目の確認ができていないため、次回ご提出時に確認いたします
**・正しいクレジットカードの情報で無い場合は、決済できない**

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by usuke-inudog** [comment]
お世話になります
下記修正いたしました。
よろしくお願いします。

[対応箇所]
①購入時、配送先の住所情報も都度入力できるようにしましょう
　→購入確認画面に登録住所が表示されるように修正し、新規登録/変更のリンクを設定しました。
②購入時、クレジットカードの情報を都度入力できるようにしましょう
　（現在は一度登録すると変更ができない仕様になっています）
　→購入確認画面上で、カード未登録の場合は新規登録へのリンクがありましたが、
　　表示がわかりづらかったため、わかりやすい表示に変更しました。
　　また、クレジットカード情報の変更はマイページから登録情報を削除→新規登録とさせていただいております。
③購入時こちらのissueに記載されているカード情報を入力しても登録が完了しないので、登録できるようにしましょう
　→カード情報の重複登録のため、Issueに記載しているカード情報を重複していない番号に変更しました

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

LGTM要件ではありませんが、issueに記載されている購入アカウントでは商品の購入ができませんでした。
新規登録したアカウントだと購入できたため、有効な購入アカウントを作成しましょう。

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
